# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
  	v.memory = 4096
  	v.cpus = 2
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.network = "private_network", ip: "192.168.0.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080	
  config.vm.provision "shell",	
  inline: "sudo add-apt-repository ppa:opencpu/opencpu-1.4 –y\
  && sudo apt-get update && sudo apt-get install opencpu-server -y"	
end
